# NOTE: Remember to update PostResDTO type after making changes here.

query getPostById($payload: PostReqDTO!) {
  getPostById(postReqDTO: $payload) {
    id
    title
    thumbnail
    content
    createdAt
    isPublished
    author {
      name
    }
    tags {
      id
      name
    }
  }
}
