# NOTE: Remember to update PostReqDTO type after making changes here.

query posts($payload: PostsReqDTO) {
  posts(postsReqDTO: $payload) {
    id
    title
    slug
    thumbnail
    content
    createdAt
  }
  totalPosts
}
