query userPosts($payload: PostsReqDTO) {
  userPosts(postsReqDTO: $payload) {
    id
    title
    slug
    thumbnail
    isPublished
    content
    createdAt
    _count {
      likes
      comments
    }
  }
  userTotalPosts
}
