# NOTE: Remember to update SignInResDTO type after making changes here.

mutation signIn($payload: SignInReqDTO!) {
  signIn(signInReqDTO: $payload) {
    id
    name
    avatar
    accessToken
  }
}
